name = "storytime-app"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "AUDIO_CACHE"
id = "a4524946344b49aea061abf423473025"
preview_id = "1bae7f4a9306422a9cbff603db080d7b"

[build]
command = "cd frontend && npm install && npm run build && cd ../backend && npm install"

[vars]
NODE_ENV = "production"
