name = "storytime-app"
type = "javascript"

[build]
command = "cd frontend && npm install && npm run build"
cwd = "./"

[build.upload]
format = "service-worker"

[[env.production.routes]]
pattern = "*/*"
zone_name = "pages.dev"
